# Generated by Django 3.2.1 on 2021-05-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
